### ISSUE TITLE
Rails Girls Kagoshima 1st とりまとめ Issue

### ISSUE THREAD

**Issue by yoshikouki** [railsgirls-jp/kagoshima#1]
2022年の6月頃を目標に Rails Girls Kagoshima を開催します

鹿児島 初！2020年にコロナの影響で断念した企画をリブートします

---

声をかけて集まった運営メンバーでキックオフを開催
4/4(月) 19:00〜

タスクの管理方法もそこで話し合います

- 当リポジトリに Issue を立てて、1タスク=1ToDoとする
https://github.com/railsgirls-jp/kobe/issues を参考にする
- 当 Issue を「タスク取りまとめの場所」として、必要であれば Issue を立てる形にする

**Comment by yoshikouki** [comment]
# 運営キックオフのアジェンダ

- 運営チームの顔合わせ
- Rails Girls Kagoshima の大枠を認識合わせ
- 今後の動きについて認識合わせ
- 次回MTGの日程をそれまでにやっていくこと

タスクは Rails Girls の開催ガイドを元に洗い出す
- https://railsgirls.jp/guide (世界標準)
- https://railsgirls.jp/getting-started-jp (日本独自の補足)

**Comment by yoshikouki** [comment]
Public Project を作成したので、以後のタスク管理はこちらで進めていきます

https://github.com/orgs/railsgirls-jp/projects/1/views/2?layout=board

**Comment by hsbt** [comment]
👋  RG JP の方から来ました。RG JP にはスポンサーがついてまして、今年は Hey さんが通年スポンサー、 Kagoshima には GMO ペパボ(と募集した企業)から運営資金の支援ができると思います。なので、必要に応じて飲食や備品の経費精算はご連絡ください。

この辺、どういうイベントにするか、次第でもあるので「どゆこと?」ということがあれば教えてください。

**Comment by yoshikouki** [comment]
Rails Girls ページ
http://railsgirls.com/kagoshima-2022.html

イベントページ
https://railsgirls-kagoshima.connpass.com/event/246553/

コーチ募集ページ
https://railsgirls-kagoshima.connpass.com/event/248131/

スポンサー募集フォーム
https://forms.gle/xx6gtZk5oBsMGstH7

チームのタスク管理など
https://docs.google.com/spreadsheets/d/1Vt-GVm-OiN4OHhlKKtLR0K4S4LwOW0oiaulRx_O-XKw/edit#gid=339538093

会計管理シートは Rails Girls Japan の協力で提供された様式を使った。詳しくは「Rails Girls Japan によるイベントの会計サポート」の項
https://railsgirls.jp/about

参加者配付資料
https://docs.google.com/document/d/1sVbARxhilz3je9q-RHe_PpiI90WtEmIHevuLlVVXbEc/edit

参加者配付用スポンサー一覧
https://docs.google.com/document/d/1zi5e0-7xEdaWUumhgcOi22svjIQzt_EHM14THlAHrw4/edit

取材対応用資料
[Rails Girls Kagoshima 1st ご取材用資料.pdf](https://github.com/railsgirls-jp/kagoshima/files/9035765/Rails.Girls.Kagoshima.1st.pdf)

Twitter と Slack のQRコード (Slack はconnpassメールでURLを送ったので、実際不要だった)
[Rails Girls Kagoshima 1st QRコード一覧 (1).pdf](https://github.com/railsgirls-jp/kagoshima/files/9035788/Rails.Girls.Kagoshima.1st.QR.1.pdf)

**Comment by yoshikouki** [comment]
2日目開会後のイントロダクション資料
https://docs.google.com/presentation/d/1JTerCIY7w-T54XKTOX8R_KN9F6MaflO2HVTVwSXxaPI/edit?usp=sharing

**Comment by yoshikouki** [comment]
2テレビ局で報道された

KYT
https://www.kyt-tv.com/nnn/sp/news104zk034tk6ui93n2c0.html

MBC
https://www.mbc.co.jp/news/article/2022063000057235.html
