### ISSUE TITLE
2022-04-19 運営MTG #2

### ISSUE THREAD

**Issue by yoshikouki** [railsgirls-jp/kagoshima#4]
# アジェンダ

1. スケジュールについて共有・フィードバック
2. 次のMTGまでのタスクの担当を決める
3. ラフが上がったロゴの決定

**Comment by yoshikouki** [comment]
# スケジュール
https://docs.google.com/spreadsheets/d/1Vt-GVm-OiN4OHhlKKtLR0K4S4LwOW0oiaulRx_O-XKw/edit#gid=0

# ロゴのラフ



|1 |2 |3 |4 |5 |6
|---|---|---|---|---|---
|![S__227614726](https://user-images.githubusercontent.com/53972292/163970777-480f7c5b-9d2f-4187-824e-e8f44816100f.jpg)|![S__227614728](https://user-images.githubusercontent.com/53972292/163970792-37998ecd-8d0a-4070-9b26-216e0e8d0c06.jpg)|![S__227614729](https://user-images.githubusercontent.com/53972292/163970795-5a1f098c-ce9a-4b9d-822f-5abe0db0d0f7.jpg)|![S__227614730](https://user-images.githubusercontent.com/53972292/163970800-fd12db4d-35f4-4ba3-9303-1bd44b45c848.jpg)|![S__227614731](https://user-images.githubusercontent.com/53972292/163970803-0a02ca95-4e3c-40ad-b100-c1abde5abfe2.jpg)|![S__227614732](https://user-images.githubusercontent.com/53972292/163970806-d1aa6387-f365-4e8d-9717-8c1bf413baff.jpg)

**Comment by yoshikouki** [comment]
- 参加者がいないと始まらないので、急ぎ公開したい
- 参加者はMax10名くらいで良さそう

**Comment by yoshikouki** [comment]
6月末に開催することが決定

**Comment by yoshikouki** [comment]
ロゴは1で決定

![PixelSnap 2022-04-19 at 18 57 03@2x](https://user-images.githubusercontent.com/53972292/163979103-2394bc5e-bb45-45e0-a1f0-b75ff10feb83.png)

**Comment by jasmine-tokudome** [comment]
【MEMO】
- 2週間に1回くらいの頻度（タスクの締めを目安）で担当を決めていく
- 次回はGWをさけ5月9日開催。
- 申し込みフォームはGW前が良さそう（そのほかのタスクの期限は詳細を確認してみる）。
- 予定表No.17、18 はGW後にする(修正済)
- 予定表No.6〜13ははやぴさんが把握されているためサポート可能。
- [Shout outとは？](http://railsgirls.com/inyourcity)（英語での宣言！前回準備したものを修正していく形で良さそう）
- 予定表No.7〜9については期日厳守で遅らせることはできない（※次回話し合う）
- 6月末開催で決定！（コロナの感染者数確認）

参照：
[Rails Girls イベントを開始させる手順](https://railsgirls.jp/getting-started-jp)

**Comment by jasmine-tokudome** [comment]
次回：5月9日19：00〜
