### ISSUE TITLE
【覚書】会場設営・備品関係・スイーツ手配

### ISSUE THREAD

**Issue by jasmine-tokudome** [railsgirls-jp/kagoshima#6]
### Rails Girlsの文字パネルを作成。
　全体の写真撮影に備えて準備。
　ラミネートした（機械はオフィスにはないので手持ちのものを使用）
　厚さは100で十分。
　赤の色味を出せずに苦労した。
　次回作るなら[こちら](https://speakerdeck.com/railsgirls)を目安に作ると良さそう。

### ガーランド
　既製品をダイソーで調達。
　また折り紙を使用して自作。
　こちらの素材を印刷して使ってみたり。
　低コストで賑やかな雰囲気は出せたかも？

### ハートの装飾
　下記参照に作成。
　ただ、画用紙だと重くて落ちてしまう。
　また壁に設置するのが難しかった。

　参照：[花嫁さんにおすすめなの飾り付けアイテム、ハートのペーパーガーランド♡](https://marry-xoxo.com/articles/5746)
　
### [RailｄGirlsの素材](https://speakerdeck.com/railsgirls)活用
　A4で印刷して壁にポスト。
　赤の色を綺麗に出すのにコンビニ印刷を利用した。

### バルーン
　ダイソーで（ハート大＋丸5個入り）4種ほど調達。
　大きく雰囲気が変わり好評だった（いくつか割れたけど。）
　メディアの多く集まる出入り口付近の設置はどうしても触れてしまいがちでNG。
　また、空調の影響を受ける。
　複数のバルーンをくっつけるのもかわいい。
　リボンは必須（1センチ幅くらいの細めのリボンを赤〜ピンクのグラデ＋ゴールド系）
　中にパーツが入っているものは静電気で浮き上がらせることができる。
　参照：[風船の中にコンフェッティを綺麗につける方法](https://www.youtube.com/watch?v=uDDn0Q34jMU) 

### ペーパーフラワー
　壁への設置を試すがうまくいかず・・・サイズ感で難しかったのかも。

### スターモチーフなど壁を飾るもの
　ホワイトボードの隙間やちょっと寂しい空間を埋めるのに使用。
　星と円形。ゴールドとシルバーなど小さいのでインパクトのある色を選択。
　参照：[【ダイソー】ホームパーティのときは壁をデコってフォトスポットに！飾りつけに便利なパーティグッズ](https://saita-puls.com/16850)

### マスキングテープ
　壁につけるのに見える部分はマステを使用。
　セロハンテープは照明に反射し意外と目立つ。
　ゴールドとグリーン系がよく選ばれてた。

### ホワイトボード
　お絵かきの上手な方達のおかげでずいぶん華やかにできた。
　インストールディに参加者に意気込みを書いていただいた。

### フォトプロップス
　作成いただき、ラミネートして切り取り。
　持ち手はストローで。
　写真を見返すとみんな持ってるのは一体感があってよかった。

### ペーパーファン
　ダイソーで調達。
　他の飾りと組み合わせて使用。
　壁の色と合わせると馴染んで使いやすい。
　今回は青系とゴールド系。低価格だけどほどほど大きめサイズで存在感あり。
　当日はマステ＋セロハンテープで落ちずにすんだ。

**【次回あったら良いかも】**

### 養生テープ
　剥がしやすいけどマステやセロハンテープより粘着力は強め。
　設置箇所によりエアコンの風を受けて落ちやすい。
　セロハンテープでは難しいこともあったのでこちらが良さそう。
　最も落ちてしまったのはバルーン。他は落ちなかった。

### リボン
　多めに買っておいて壁に這わせるだけても可愛かったかも。

【参照：フォトプロップ使えそうなサイトまとめ】

 http://nicowedding.com/photoprops/images/props26.jpg

 http://nicowedding.com/photoprops/images/02.pdf

 http://nicowedding.com/photoprops/images/props14.pdf

 http://nicowedding.com/photoprops/images/props23.pdf

 http://nicowedding.com/photoprops/images/props17.pdf

 http://nicowedding.com/photoprops/images/props24.pdf

 http://nicowedding.com/garland/images/tag04.png

 http://nicowedding.com/garland/images/tag05.png　

## 備品関係

まず、必要なものと欲しいものを分けずに洗い出し。

![iOS の画像 (5)](https://user-images.githubusercontent.com/103996128/177320705-62068e96-c862-4e0c-b032-5476f5085044.jpg)

その後、必要なものと優先順位を決めた。

最初はスポンサー料が不明だったため、
高価格なものの発注（フォトフレームなど）は控え
自作する方向で検討。

フォトフレームは注文から届くまでにある程度の日数が必要な点に注意。

**【実際使用したもの】**

### スタッフの腕章
　オフィスにあったものを使用

### 名札
　調達。中の紙は[こちらの素材](https://speakerdeck.com/railsgirls/nametags)を印刷、カットして使用。
　参加者はルビー、エンジニアはユニコーンなどとキャラを変えてみた。
　Conpassではニックネームだったため、事前準備不可。
　　開催時の受付にサインペンと紙を準備、ご本人に読んで欲しい名前を書いていただいた。

### クッキングシート
　おやつ類を並べるのに使用

### 小さなゴミ袋
　お手洗いのゴミの回収のために。
　参加者が多いと頻繁に確認が必要。
　余っているので次回以降も使えるはず。

### ゴミ袋（テーブル用）
　起立するタイプの小さめサイズをテーブルに。
　お菓子のゴミをまとめておくために。
　結構いっぱいになっていた。

### 紙皿
　ダイソーで可愛いものを選択。
　テーブルごとにお菓子を用意するのに使用。

### マステやガーラントなど（会場設営の方で記載）

参照：[備品洗い出しスレ](https://railsgirlsjp.slack.com/archives/C038QAJCHNY/p1652421418302099)

## スイーツ手配

候補は[こちら](https://docs.google.com/spreadsheets/d/1Vt-GVm-OiN4OHhlKKtLR0K4S4LwOW0oiaulRx_O-XKw/edit#gid=943158757)。

店舗名 | コメント | 提供タイミング | 価格 | 場所 | 電話番号 | Map |
・[フルーツ大福専門店BRAN KAJITSU ](https://www.brankajitsu.com/)
 鹿児島市上荒田町３５−２３
099-297-6058
 [Map](https://www.google.com/maps/place/%E6%97%A5%E6%9C%AC%E3%80%81%E3%80%92890-0055+%E9%B9%BF%E5%85%90%E5%B3%B6%E7%9C%8C%E9%B9%BF%E5%85%90%E5%B3%B6%E5%B8%82%E4%B8%8A%E8%8D%92%E7%94%B0%E7%94%BA%EF%BC%93%EF%BC%95%E2%88%92%EF%BC%92%EF%BC%93/@31.5744556,130.5434402,17z/data=!3m1!4b1!4m5!3m4!1s0x353e6737ca87f7dd:0x1de77b6b8ffe5b2d!8m2!3d31.5744556!4d130.5456342?hl=ja )

・[oyatsuya sun simai ](https://www.instagram.com/oyatsuya_sunsimai/)（おやつや.さんしまい）
少し遠いのが気がかり。
鹿児島市田上８丁目 
[Map](https://www.google.com/maps/place/oyatsuya+sun+simai+%EF%BC%88%E3%81%8A%E3%82%84%E3%81%A4%E3%82%84.%E3%81%95%E3%82%93%E3%81%97%E3%81%BE%E3%81%84%EF%BC%89/@31.5855827,130.5096338,15z/data=!4m5!3m4!1s0x0:0x71aec9e64ce3e89d!8m2!3d31.5855827!4d130.5096338)

[くじらカフェ](https://kujira-farm.com/#ec) 
オンラインショップあり
 鹿児島市鴨池 
[Map](https://www.google.com/maps/place/%E3%81%8F%E3%81%98%E3%82%89%E3%82%AB%E3%83%95%E3%82%A7/@31.5685898,130.5501663,15z/data=!4m5!3m4!1s0x0:0x420838fb03d6e39f!8m2!3d31.5685898!4d130.5501663)
 
[Veda Sultenfuss](https://vedasultenfuss.stores.jp/?category_id=613011448a457211d2b173c2) 
焼き菓子ギフト可能との記載あり。お取り寄せ。

[明石屋](https://www.akashiya.co.jp/products/baumkuchen/)
中央駅付近で調達用意。 
バウムクーヘン1個280円くらい
鹿児島市中央町 
[Map](https://www.google.com/maps/place/%E6%98%8E%E7%9F%B3%E5%B1%8B+%E4%B8%AD%E5%A4%AE%E5%BA%97/@31.5854663,130.5387872,17z/data=!3m1!4b1!4m5!3m4!1s0x353e674ff84a9e09:0x2267c6237629ed24!8m2!3d31.5854681!4d130.5432552)

[Andenken ](https://andenken.jp/)
クッキーが美味しい

[じねんや ](http://jinen-ya.com/)
チーズケーキ（チーズスティックタルト？）が美味しい

【実際に使用した店舗とメモ】

### [フルーツ大福専門店BRAN KAJITSU ](https://www.brankajitsu.com/)
果物は日替わりで価格は時価。セット価格がお得でそれだと一つ560円くらい。
先に予算と個数を伝え、その範囲で用意してもらった。
当日が賞味期限なので、当日受け取りに行く。
要冷蔵だが冷蔵庫はドリンクが入っており空きを確認しつつ乾杯前に受け取りへ。
オフィスからは近い。
当日持ち帰りが多かったので、ひとつづつ包んでもらう方が良かったかもと思った。

### [Andenken ](https://andenken.jp/)
焼き菓子（4種）とバームクーヘンをそれぞれ一つずつ。
バームクーヘンは小包装でギフト感があった。
当日午前にオフィスに直接お届けいただく。
個数が多いと欠品がありうるので早めの注文が良い。
9時から集まっているとお昼前に「お腹が空いた」の声が聞かれ
ランチ後ではなくランチ前にお渡しした。
カラーミーショップを使ってくださっているショップ様。

参照：[相談していたスレ](https://railsgirlsjp.slack.com/archives/C038QAJCHNY/p1655774409390399?thread_ts=1655772838.596389&cid=C038QAJCHNY)

ref: https://github.com/railsgirls-jp/kagoshima/issues/1

**Comment by yoshikouki** [comment]
最高です！！！
お疲れ様でした！
